### ISSUE TITLE
大小写导致run dev出错

### ISSUE THREAD

**Issue by yangbit** [shenghy/jspangAdmin#2]
### /src/components/common/Home.vue第13行和第14行调用存在大小写报错
```
    import vHead from './Header.vue';
    import vSidebar from './Sidebar.vue';
```

需要把
> /src/components/common/header.vue和sildebar.vue

文件名改成首字母大写@shenghy
才可以正常npm run dev

环境
> ubuntu 16.10(4.8.0-44-generic), node7.7.4, npm4.5.0

工程环境,终端目录里看是webpack2.3.2,vue2.26
package.json里面是webpack@^2.2.1,vue@^2.2.1

希望对你有帮助. :+1:

**Comment by shenghy** [comment]
好的，我会重视这个问题，近期修复，感谢。

**Comment by shenghy** [comment]
这个问题已经修改了，非常感谢你的帮助。
